Blogtastic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")),
    path("about/", views.about),
    path("", article_views.article_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    # path("profile/", views.profile, name="profile"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"


urlpatterns = [
    path("", views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path("<slug:slug>/", views.article_detail, name="detail"),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# to add new field to the model use the following command:
# python3 manage.py makemigrations
# then type:
# python3 manage.py migrate


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateField(auto_now_add=True)
    thumb = models.ImageField(default="default.png", upload_to="thumbnails")
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:75] + "..."

articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ["title", "body", "slug", "thumb"]

Blogtastic/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home_page(request):
    return render(request, "homepage.html")


def about(request):
    return render(request, "about.html")

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form1 = form
            user = form1.save()
            # log the user in
            login(request, user)
            return redirect("articles:list")
    else:
        form = UserCreationForm()
    return render(request, "accounts/signup.html", {"form": form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("articles:list")

    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html", {"form": form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("articles:list")

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by("-date")
    return render(request, "articles/article_list.html", {"articles": articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, "articles/article_detail.html", {"article": article})


@login_required()
def article_create(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect("articles:list")
    else:
        form = forms.CreateArticle()
    return render(request, "articles/article_create.html", {"form": form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %} {% block content%}
<h1>Log in</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %} {{ form }} {% if request.GET.next %}
  <input type="hidden" name="next" value="{{ request.GET.next }}" />
  {% endif %}
  <input type="submit" value="Login" />
</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %} {% block content%}

<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
  {% csrf_token %} {{ form }}
  <input type="submit" value="Signup" />
</form>

{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %} {% block content %}
<div class="create_article">
  <h1>Create an Blog</h1>
  <form
    class="site-form"
    action="{% url 'articles:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %} {{form}}
    <input type="submit" value="Create" />
  </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends "base_layout.html" %} {% block content %}
<div class="article-detail">
  <div class="article">
    <img src="{{ article.thumb.url }}" alt="not working" />
    <h2>{{ article.title }} by {{article.author}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends "base_layout.html" %} {% block content %}
<h2 class="article-list-title">
  <u>Discussions</u>
</h2>
<p></p>
<div class="articles">
  {% for article in articles %}
  <a href="{% url 'articles:detail' article.slug %}">
    <div class="article-in-list">
      <h2>{{article.title}}</h2>
      <p>{{article.snippet}}</p>
      <p>{{article.date}}</p>
      <p class="author">By {{article.author}}</p>
    </div>
  </a>
  {% endfor %}
</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>About</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
</head>

<body>
    <script src="" async defer></script>
    <h1>ABOUT</h1>
    <p>Welcome to Blogtastic</p>
</body>

</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Blogtastic</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}" />
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>

<body>
  <div class="wrapper">
    <h1><a href="{%url 'home'%}">Blogtastic</a></h1>
    <nav class="NavButtons">
      <ul>
        {% if user.is_authenticated %}
        <li>
          <form
            class="logout-link"
            action="{% url 'accounts:logout' %}"
            method="post"
          >
            {% csrf_token %}
            <button type="submit">
              <a href="{% url 'accounts:login' %}"></a>Logout
            </button>
          </form>
        </li>
        <li>
          <a href="{% url 'articles:create' %}" class="highlight"
            >Create Blog</a
          >
        </li>
        {% else %}

        <li><a href="{% url 'accounts:login' %}">Login</a></li>
        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>

        {% endif %}
      </ul>
    </nav>
    {% block content %} {% endblock %}
  </div>
</body>

templates/homepage.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Homepage</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
</head>

<body>
    <script src="" async defer></script>
    <h1>HOME</h1>
    <p>Welcome to Blogtastic</p>
</body>

</html>